In [1]:
# 수치미분 1차버전 numerical derivative

def numerical_derivative(f, x):
    delta_x = 1e-4 # 델타 값은 아주 미세한 값. 너무 작은 값을 입력하면 값이 안 나올 수 있음. 경험적으로 1e-4 정도를 사용
    return (f(x+delta_x)-f(x-delta_x)) / (2*delta_x)

def my_func1(x):
    return x**2

result = numerical_derivative(my_func1, 3)
print(result)

6.000000000012662


In [3]:
# [예제2] f(x) = 3xe^x

import numpy as np

def my_func2(x):
    return 3*x*(np.exp(x))

result2 = numerical_derivative(my_func2, 2)
print(result2)

66.50150507518049


In [20]:
# 다변수함수의 경우 입력변수는 서로 독립적이기 때문에 수치미분 또한 변수의 개수만큼 개별적으로 계산해야 함

# [예] f(x,y) : f'(1, 2) 값을 계산하기 위해서는 1) x=1에서의 미분계수는 변수 y=2를 상수로 대입하여 미분하고, 2) y=2에서의 미분계수 또한 변수 x=1을 상수로 대입하여 미분, f'(1,2)=(8,15) 이런식으로 표현

import numpy as np

def numerical_derivative(f, x): # f는 다변수함수, x는 모든 변수를 포함하고 있는 numpy 객체(배열, 행렬)
    delta_x = 1e-4
    grad = np.zeros_like(x) # 우리가 계산한 수치미분 값을 저장, 입력으로 들어온 x에 맞추어, 현재 0으로 초기화
    print("grad = ", grad)
    it = np.nditer(x, flags=['multi_index'], op_flags=['readwrite']) # 모든 입력변수에 대해 편미분하기 위해 iterator 획득, np의 모든 원소를 가리키기 위해?
    print("it = ", it)
    
    while not it.finished: # 변수 개수만큼 반복
        idx = it.multi_index
        print("idx = ", idx)
        
        tmp_val = x[idx] # np 타입은 mutable 이므로 원래값 보관
        print("tmp_val = ", tmp_val)
        
        # 하나의 변수에 대한 수치미분 계산
        x[idx] = float(tmp_val) + delta_x 
        fx1 = f(x) # f(x+delta_x)
        print("fx1:", fx1)
        
        x[idx] = tmp_val - delta_x
        fx2 = f(x) # f(x-delta_x)
        print("fx2:", fx2)
        
        grad[idx] = (fx1 - fx2) / (2*delta_x)
        
        x[idx] = tmp_val # 보관되어 있던 원래값 다시 가져옴값 다시 가져옴
        it.iternext() 
        print("grad = ", grad)
        
    return grad

def func1(input_obj): # input_obj: 벡터나 행렬을 나타내는 np 객체, 수치미분함수에서 두 번째 객체를 x로 받기 때문에~
    x = input_obj[0]
    return x**2

numerical_derivative(func1, np.array([3.0]))

grad =  [0.]
it =  <numpy.nditer object at 0x0000021BC5492F30>
idx =  (0,)
tmp_val =  3.0
fx1: 9.000600010000001
fx2: 8.999400009999999
grad =  [6.]


array([6.])

In [21]:
def func2(input_obj):
    x = input_obj[0]
    y = input_obj[1]
    return 2*x + 3*x*y + y**3 # np.power(y,3) 다른 표현

input = np.array([1.0, 2.0])

result3 = numerical_derivative(func2, input)
result3

grad =  [0. 0.]
it =  <numpy.nditer object at 0x0000021BC5492F30>
idx =  (0,)
tmp_val =  1.0
fx1: 16.000799999999998
fx2: 15.9992
grad =  [8. 0.]
idx =  (1,)
tmp_val =  2.0
fx1: 16.001500060001003
fx2: 15.998500059999
grad =  [ 8.         15.00000001]


array([ 8.        , 15.00000001])

In [24]:
def func3(input_obj):
    w=input_obj[0,0]
    x=input_obj[0,1]
    y=input_obj[1,0]
    z=input_obj[1,1]
    
    return( w*x + x*y*z + 3*w + z*np.power(y,2))

input = np.array([[1.0, 2.0], [3.0, 4.0]])
numerical_derivative(func3,input)

grad =  [[0. 0.]
 [0. 0.]]
it =  <numpy.nditer object at 0x0000021BC54B28F0>
idx =  (0, 0)
tmp_val =  1.0
fx1: 65.0005
fx2: 64.9995
grad =  [[5. 0.]
 [0. 0.]]
idx =  (0, 1)
tmp_val =  2.0
fx1: 65.0013
fx2: 64.9987
grad =  [[ 5. 13.]
 [ 0.  0.]]
idx =  (1, 0)
tmp_val =  3.0
fx1: 65.00320004000001
fx2: 64.99680004
grad =  [[ 5. 13.]
 [32.  0.]]
idx =  (1, 1)
tmp_val =  4.0
fx1: 65.0015
fx2: 64.99849999999999
grad =  [[ 5. 13.]
 [32. 15.]]


array([[ 5., 13.],
       [32., 15.]])